FROM apache/airflow:2.9.3

USER airflow
RUN pip install --no-cache-dir \
    requests>=2.31 \
    pydantic>=2.0 \
    pydantic-settings>=2.0 \
    python-dotenv>=1.0 \
    google-cloud-storage>=2.10 \
    google-cloud-bigquery>=3.11 \
    google-cloud-secret-manager>=2.16
